apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAQwV061Q57gCG7GFMJTfP5r5AtLUzgc6sGeN1V6O9R0KTPV1Gv/PzFD6xFatiZbWqac2YCA3Pz7AxyJEsvlbFOhkKXch31AKTYGk6YgRKYkqIarkXqicPQe7K5vh2Ap0M0em4O41IDWK5uIydsZPrmj6POLmkIbZ/NpMeNRYB+2hyWX7d7isI/VVp0eCrsgeoCWA0QPdkA6gQCfwNtIyVx7txZSI2xgQwMsbWFkc+2PTQh7vPi6NiXL5gvUlUEfmL3MwJPsZ2fHdYmAYPWMh898EcGMQXHnXjGzB8rRdEE+w0q/F5VTgoyTCSwhbNnJAWaxz0g/NDz3LdOdeo82AsKtcZgsbgHa6Tf81d1TVT2XRzW82PrR8NINtfJtILVwGZ5DQoF4q/H5KelYyW3rFeKG4yP0UZGWZMr7VqOE8X+IqiXGoreAL8hsyG3LafgnowVv0SGwIg/PlGhghBlC/PWRE1tW2zSYnrBfUst22LOiULBkLa/sDeNprQvqEyvIYLSmSAR/CQpvLke5vpaEDuMhyIyoRNLqmn5+r/BJA7q265BX5jOAURh4EuCaEwBQTYxJ8RGvNDXSUhcfLcSu2+TQIoRGBxjFGbiAS5CMJOeCjM3Ob9lHfcPHheJQGrgwnXQQC/Hl0khdqQUJ0Ji2tz7fK+g/EFIwN6tQqe2AAAeGxG2On3qgZgVippYxgiIAl0+dJoMhi1Qc2nVEzqqfAqI18xLeQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
