apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/lcolagio/lab-tekton-taxi-gitops-2.git?ref=HEAD
  creationTimestamp: null
  name: dev
spec: {}
status: {}
